m3_rotors = {'ETW'  : ['ABCDEFGHIJKLMNOPQRSTUVWXYZ', '', '', 0],
             'I'    : ['EKMFLGDQVZNTOWYHXUSPAIBRCJ', 'Y', 'Q', 1],
             'II'   : ['AJDKSIRUXBLHWTMCQGZNPYFVOE', 'M', 'E', 1],
             'III'  : ['BDFHJLCPRTXVZNYEIWGAKMUSQO', 'D', 'V', 1],
             'IV'   : ['ESOVPZJAYQUIRHXLNFTGKDCMWB', 'R', 'J', 1],
             'V'    : ['VZBRGITYUPSDNHLXAWMJQOFECK', 'H', 'Z', 1],
             'VI'   : ['JPGVOUMFYQBENHZRDKASXLICTW', 'HU', 'ZM', 2],
             'VII'  : ['NZJHGRCXMYSWBOUFAIVLPEKQDT', 'HU', 'ZM', 2],
             'VIII' : ['FKQHTLXOCBJSPDZRAMEWNIUYGV', 'HU', 'ZM', 2],
             'UKW-B': ['YRUHQSLDPXNGOKMIEBFZCWVJAT', '', '', 0],
             'UKW-C': ['ESOVPZJAYQUIRHXLNFTGKDCMWB', '', '', 0]}